version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomation_AWSSTAGEProject
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
