version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomation_AWSSTAGEProject
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqa_gitruntimeautomation_awsstage.integrations:EdgeFlowserviceWithExistingEdS
  packages:
  - name: SIQA_GitRuntimeAutomation_AWSSTAGEProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
